version: '3.7'

services:
  reactjs:
    container_name: TemboReact
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - './node_modules/'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development